baseURL = "https://cardboardborks.com/"
theme = "borks"
title = "Cardboard Borks"

[Params]
author = "Cariad Eccleston"
banner = "/cardboardborks.svg"
copyright = "Cardboard Borks &copy; 2022 Cariad Eccleston & Alex Derbe"
fathom = "KBKNQXXD"

[Params.socials]
email = "cariad@cardboardborks.com"
instagram = "cardboardborks"

[permalinks]
  blog = '/blog/:year/:month/:title/'
